services:

  backend:
    build: ./backend
    ports:
      - "8000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - db

  bot:
    build: ./bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBAPP_URL=${WEBAPP_URL}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - backend
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: weightdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./backend/app/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
